/* Main.c file generated by New Project wizard
 * 
 * Created:   Tue Apr 21 2026
 * Processor: LPC1114FBD48/301
 * Compiler:  GCC for ARM
 */
 /*Name : tasneem rami qanoa
 ID:220210639*/

/* Define hardware register addresses for GPIO Port 0 and Port 2 */
#define GPIO0DIR (*((volatile unsigned long *)0x50008000)) 
#define GPIO0DATA (*((volatile unsigned long *)0x50003FFC)) 
#define GPIO2DIR (*((volatile unsigned long *)0x50028000)) 
#define GPIO2DATA (*((volatile unsigned long *)0x50023FFC))

int i = 0; 

/* Basic loop delay for timing requirements */
void delay(int count) { 
    for(i = 0; i <= count; i++); 
}

/*Sends 4 bits to LCD pins D4-D7 and toggles Enable*/
void send_nibble(unsigned char n, unsigned char rs_val) {
    GPIO2DATA = (n << 4);  /* Shift data to upper pins P2.4-P2.7 */
    GPIO0DATA = rs_val | 0b100;  /* Set RS and pull Enable HIGH*/
    delay(1000); /* Wait for execution*/
    GPIO0DATA = rs_val; /* Pull Enable LOW to latch data*/
    delay(1000); 
}

/*Sends 8-bit command as two 4-bit nibbles*/
void send_cmd(unsigned char cmd) { 
    send_nibble(cmd >> 4, 0);   /*Send High Nibble with RS=0*/
    send_nibble(cmd & 0x0F, 0);  /*Send Low Nibble with RS=0*/
} 

/*Sends 8-bit character as two 4-bit nibbles*/
void send_letter(unsigned char letter) { 
    send_nibble(letter >> 4, 0b010);   /*Send High Nibble with RS=1*/
    send_nibble(letter & 0x0F, 0b010);  /*Send Low Nibble with RS=1*/
    delay(50000); /*Wait for character processing*/
} 

/* Prints a full string to the LCD*/
void send_string(char* str) {
    while(*str) send_letter(*str++); /* Send characters until null terminator*/
}

int main (void) 
{ 
    GPIO0DIR |= 0b110;  /*Set P0.1(RS) and P0.2(E) as outputs*/
    GPIO2DIR |= 0xF0;   /* Set P2.4-P2.7 as data outputs*/
    
    GPIO0DATA = 0;  /* Clear control lines*/
    GPIO2DATA = 0;  /* Clear data lines*/
 
    delay(20000);  /* Initial power-on wait*/

   /* 4-bit mode initialization sequence*/
    send_nibble(0x03, 0);
    delay(5000);
    send_nibble(0x03, 0);
    delay(200);
    send_nibble(0x03, 0);
    send_nibble(0x02, 0);  /* Force controller into 4-bit mode*/

   /* LCD Function Set and Display Configuration*/
    send_cmd(0x28);       /* 2 lines, 5x7 matrix, 4-bit mode  */
    send_cmd(0x0C);       /* Display ON, cursor OFF */
    send_cmd(0x01);       /* Clear display screen */
    delay(10000);         /* Wait for clear command */
    send_cmd(0x06);       /* Entry mode: increment cursor */

    /* Output task data */
    send_string("Tasneem Qanoa");
    send_cmd(0xC0);       /* Move to start of second line*/
    send_string("220210639");

    while (1);            /* Stop execution*/
    return 0;
}